### ISSUE TITLE
Linux source location

### ISSUE THREAD

**Issue by cinnes** [mallowigi/slack-themes#1]
Spotted that linux paths are in `lib/consts.js` and wanted to give my scenario

The current full path to `ssb-interop.js` for linux is in `consts.js` as:  `/usr/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js`.

On my machine the file was located at `/usr/lib/slack/resources/app.asar.unpacked/dist/ssb-interop.bundle.js`

```
$ find . -name ssb-interop.js
$ find . -name ssb-interop.bundle.js              
./app.asar.unpacked/dist/ssb-interop.bundle.js
```

Pointing to this directory in `consts.js` got things working for me :smile: 

For added info, I'm running on arch linux with slack installed from AUR (https://aur.archlinux.org/packages/slack-desktop/)

**Comment by mallowigi** [comment]
I'll be glad if you made a PR :)
