### ISSUE TITLE
Background Color in Threads isn't applied

### ISSUE THREAD

**Issue by curiosity26** [mallowigi/slack-themes#15]
<img width="407" alt="redacted-thread-slack" src="https://user-images.githubusercontent.com/4050934/67510104-37292680-f649-11e9-812d-d46c0d65af1e.png">

The background color on thread messages is always white and is hard to read for darker themes. I've tried all of the darker themes. The black boxes in my screen shot are redacted info.

Slack Version: 4.0.3
Git Master Branch Commit Hash: e26537173efd3c365ab23f3d4768ddfa3923d948

**Comment by curiosity26** [comment]
Mouse hover over the message correctly uses the background hover color. New messages in the thread are also highlighted correctly. It's only old messages in a thread and the master message itself.

**Comment by curiosity26** [comment]
Found a temporary work around. In Slack 4.0.3, Dark Mode was introduced. If you want to use a dark theme, you can fix the threads background issue by doing the following:

1. Disable your Slack Theme you applied in this repo
2. Reopen Slack and go to your Preferences > Themes > Choose Dark
3. Apply the Dark theme from this repo
4. Restart Slack

Now your thread messages should have a dark background, hopefully with the color from the theme, but anything is better than white text on a white background.

**Comment by mallowigi** [comment]
Hi sorry for the lack of response. I could not reproduce this, in my window the thread messages are the same colo ras the background...

**Comment by curiosity26** [comment]
With slack version 4.0.3 or newer on Mac? I tracked down the css that was
causing the override but couldn’t override that css declaration for some
reason. Changing to default dark mode And then applying the theme worked.

**Comment by mallowigi** [comment]
I genuinely have no idea. Sorry about that!
