### ISSUE TITLE
White text on yellow background for unread message

### ISSUE THREAD

**Issue by DanielHilton** [mallowigi/slack-themes#16]
I'm using the Monokai Pro theme if that helps. I can't inspect the element as it disappears from Slack so I'm not quite sure what in the styles needs to be fixed.

<img width="1293" alt="Screenshot 2019-10-30 at 16 40 38" src="https://user-images.githubusercontent.com/28859662/67878980-17f03480-fb34-11e9-9230-4f77d7278ab2.png">

**Comment by mallowigi** [comment]
Yeah, it looks like the accent color is too bright. I'll replace it with another color since I can't change the selected text color.

**Comment by mallowigi** [comment]
I won't replace the accent color as I like it for most usages, but now thanks to the tweaks you can change to a custom accent color.
