### ISSUE TITLE
Text formatting toolbar background colour mismatch

### ISSUE THREAD

**Issue by sguillema** [mallowigi/slack-themes#20]
When the input is selected:
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/15685678/70963957-27c0d980-20de-11ea-9fde-2783a9619a08.png">

When it isn't selected, it is the correct colour:
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/15685678/70964003-5474f100-20de-11ea-9ee0-dd51fb1ed310.png">

I am using Atom One Dark, but this occurs on other themes also. Thanks!

Edit:

Also this similarly occurs on the options hover for messages
<img width="212" alt="image" src="https://user-images.githubusercontent.com/15685678/70964114-c77e6780-20de-11ea-8db4-774830acf087.png">

**Comment by mallowigi** [comment]
fixed
