### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by Moulick** [mallowigi/slack-themes#21]
I applied by cloning the repo and running ./main. It says that `Slack successfully themed. Please restart Slack to apply the theme.` but nothing happens.

Slack version: 4.2.0
Commit sha: 41d0f81

I have rerun it several times now. no effect

**Comment by mallowigi** [comment]
Are you sure you completely closed it? Not simply pressing the close button but to quit the app completely.

**Comment by Moulick** [comment]
yep compelte quit and start, command + q

**Comment by LeanderD** [comment]
Same here. Was working great before, but not working since version 4.20

**Comment by mallowigi** [comment]
I just tried now. Try to run with `npm run apply` ?

**Comment by Moulick** [comment]
@mallowigi  Yeah. `npm run apply` works . But still `./main` method does not work :(

**Comment by mallowigi** [comment]
I'm going to change that with a binary in the near future
