### ISSUE TITLE
Cannot install a theme through slack-themes (REASON: old cli tool has been removed)

### ISSUE THREAD

**Issue by weiqitoby600** [mallowigi/slack-themes#29]
Hey team, seems it has stopped working for quite a while. I could see installation success message but nothing changed after restarting the slack. 

Current OS:  macOS Catalina 10.15.3
Current slack ver.: 4.3.3

**Comment by mallowigi** [comment]
This question will become recurrent probably, so here's what to do:

1. type `npm uninstall -g @mallowigi/slack-themes`
2. type `npm install -g mtslack`
3. type `sudo mtslack` and check that you have latest version
4. reapply

Tell me if it solves it
