### ISSUE TITLE
Details about backing up original Slack?

### ISSUE THREAD

**Issue by spencerwooo** [mallowigi/slack-themes#3]
Is there a more detailed guide on “backing up the original Slack app”? I’m a little confused. Should I just go to the Application folder and copy a full version of `Slack.app` and rename it to something else? Or is there some other way?

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by mallowigi** [comment]
In MacOS, yes, simply copy the Slack.app and create a copy.

For other OS I'm not sure yet.
