### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by RichieRunner** [mallowigi/slack-themes#32]
Consistently getting permission issue, and telling me to run with `sudo` command, even when i'm on windows using elevated privileges

![image](https://user-images.githubusercontent.com/20289967/77808795-16c32500-704a-11ea-9ab7-2f747f8c1931.png)

If this is not supported on Windows, should probably remove that from the README.

**Comment by srisar** [comment]
I can confirm as well. asking to be run as root. win 10 1909

**Comment by mallowigi** [comment]
I don't have a Windows machine sadly, so I won't be able to help on this one. If you manage to fix it, send me a PR.

**Comment by mallowigi** [comment]
Windows support is finally there!!!! And I've not tested it, but this could also work for Linux (need confirmation)
