### ISSUE TITLE
Can't apply themes

### ISSUE THREAD

**Issue by AlexanderVishnevsky** [mallowigi/slack-themes#36]
Hi there, 
when I'm tryinf to execute `npm install -g mtslack`
I have the following error:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/mallowigi/asar.git
npm ERR! Host key verification failed.
```

OS: Ubuntu 18.04.4 LTS
Version of Slack: Snap 4.4.2 64-bit

**Comment by mallowigi** [comment]
what version of mtslack ?

**Comment by AlexanderVishnevsky** [comment]
> mtslack

7.3.1

**Comment by mallowigi** [comment]
Thanks, I used a fork of a package that did not work in Windows, but it probably worked on my machine because it's my package, never tried from other machines...

Try to reinstall it, it should install v7.4.0, and tell me if that fixes the problem

**Comment by AlexanderVishnevsky** [comment]
Thanks for the answer, version v7.4.0 solved my problem
