### ISSUE TITLE
Wrong path to Slack on Ubuntu

### ISSUE THREAD

**Issue by AlexanderVishnevsky** [mallowigi/slack-themes#37]
## Current Behavior 🐞
Wrong path when trying to apply theme on Ubuntu
![image](https://user-images.githubusercontent.com/26820006/79837782-adb99d80-83ba-11ea-955a-bb2103618fdd.png)
## Expected Behavior 🧐
Change path to` /snap/slack/23/usr/lib/slack/resources` for slack, installed from Market
## Environment 🎮

Tech | Version
-- | --
MTSLACK | v7.4.0
Ubuntu | v18.04.4 LTS

**Comment by mallowigi** [comment]
I don't have ubuntu (well I have it in vm, maybe i'll try there), but if you find something that works, you're welcome to do a PR :)

**Comment by mallowigi** [comment]
I think i fixed it in last
