### ISSUE TITLE
Theme stuck?

### ISSUE THREAD

**Issue by frackleton** [mallowigi/slack-themes#39]
Mac OS Catalina 10.15.4 (19E287). I seem to be stuck on the first theme I selected (Material Oceanic) even after removing the theme, restarting slack and confirming default coloring, and then installing a new theme.

**Comment by mallowigi** [comment]
True, I need to write a doc about it but I have other priorities at the moment

The apply method has actually completely changed, even though there are still options to the console they will not do anything anymore as it has been replaced by the `Loop over installed themes` button in the title bar.

**Comment by weiqitoby600** [comment]
It looks like no matter which theme is chosen during the `apply theme`, the Material Oceanic is always applied.

MacOS Catalina 10.15.4
Slack: 4.5.1

**Comment by frackleton** [comment]
following up; there is` no Loop over installed themes` button in the title bar.

**Comment by jwssdwed** [comment]
Facing the same problem, the `Material Oceanic` is the only theme applied.

Mac OS: 10.15.5 (19F101)
Slack Version 4.6.0

**Comment by ellisvalentiner** [comment]
@frackleton launch slack with developer mode and it should be there

```sh
export SLACK_DEVELOPER_MENU=true; open -a /Applications/Slack.app
```

**Comment by diegoulloao** [comment]
Same problem...

**Comment by mallowigi** [comment]
Please make sure you have the latest update

**Comment by diegoulloao** [comment]
Recently installed and is not working, output is:

```
? Please select an command Apply theme
Removing theme...

Successfully removed!

current theme is now Material Oceanic
Adding Theme Code to Slack...

Slack successfully themed. Please restart Slack to apply the theme.
```

Can't choose...

**Comment by mallowigi** [comment]
https://github.com/mallowigi/slack-themes#loop-over-selected-themes

--
Elior
