### ISSUE TITLE
Can't apply themes on new Slack version on MacOS and Linux

### ISSUE THREAD

**Issue by TamasBarta** [mallowigi/slack-themes#41]
Hi,

Slack transitioned to the [new layout](https://slack.com/intl/en-hu/help/articles/360043092173-The-new-Slack-experience-for-desktop) on my computer, and now I cannot apply the themes anymore. I installed Slack using brew on MacOS and yay on Linux. `mtslack` can find Slack on both, says theme is applied successfully, but the themes are not visible when running Slack anymore. Of course I reapplied them many times, restarted Slack many times, didn't work :(

**Comment by mallowigi** [comment]
I literally tried minutes ago and it worked... can you tell me which version of mtslack you're using ?

**Comment by TamasBarta** [comment]
I realized I forgot to mention the version much later, sorry. I'm using version 8.0.0.

**Comment by TamasBarta** [comment]
Looking at the issues I concluded too that it should work, so I was surprised as well. Can I provide any further info? 

This is my output in the terminal:

```
  ____  _            _      _____ _                              _                _ _           
 / ___|| | __ _  ___| | __ |_   _| |__   ___ _ __ ___   ___     / \   _ __  _ __ | (_) ___ _ __ 
 \___ \| |/ _` |/ __| |/ /   | | | '_ \ / _ \ '_ ` _ \ / _ \   / _ \ | '_ \| '_ \| | |/ _ \ '__|
  ___) | | (_| | (__|   <    | | | | | |  __/ | | | | |  __/  / ___ \| |_) | |_) | | |  __/ |   
 |____/|_|\__,_|\___|_|\_\   |_| |_| |_|\___|_| |_| |_|\___| /_/   \_\ .__/| .__/|_|_|\___|_|   
                                                                     |_|   |_|                  
version 8.0.0 by @mallowigi
Welcome to the Slack Theme Applier CLI!

Please note that this is still experimental and can ruin your Slack application! In the case of a problem, please reinstall Slack.

? Please select an command Apply theme
Removing theme... 

Successfully removed!

current theme is now Material Oceanic
Adding Theme Code to Slack... 

Slack successfully themed. Please restart Slack to apply the theme.
```

**Comment by mallowigi** [comment]
Perhaps, try to reinstall slack from scratch and apply the theme then?

**Comment by TamasBarta** [comment]
Okay, that worked, and I just realized, as I failed to remove Slack with Brew, that probably my company computer came with Slack preinstalled, and it may have caused the issues. Pretty stupid error on my end, sorry about that. I checked, and the Linux version worked without reinstalling, I probably used an earlier version of mtslack on Linux, and I didn't realize it. Thanks for helping!
