### ISSUE TITLE
Can't choose slack theme via "Apply Theme"

### ISSUE THREAD

**Issue by etwei-linkedin** [mallowigi/slack-themes#43]
Hey Team, 

I recently found that mtslack never allowed me to choose a slack theme when I selected "Apply Theme" option, instead, it always set Material Oceanic. Is this a known issue? Or is there anything I missed? Thank you!

<img width="1195" alt="Screen Shot 2020-07-08 at 3 15 18 PM" src="https://user-images.githubusercontent.com/66774228/86975758-dafe2800-c12d-11ea-95db-2e378508d7e2.png">

**Comment by etwei-linkedin** [comment]
Can you let me know which commit was a non-experimental (`stable`) version so that I can reset my head and choose a theme?

**Comment by mallowigi** [comment]
Everything is explained in the readme

**Comment by etwei-linkedin** [comment]
Ooo, thanks for the info! Sorry for the spam question here.

**Comment by jwssdwed** [comment]
How to solve this?

**Comment by jwssdwed** [comment]
Ah Slack Tweaks
