### ISSUE TITLE
Add ability to override monospaced font

### ISSUE THREAD

**Issue by TamasBarta** [mallowigi/slack-themes#46]
Today I set my font to a monospaced font, and found some code snippets in our Slack, and I found that that is monospaced, but uses a different font. Would love to override that as well. Of course with a separate setting. Thanks for considering adding this.

**Comment by mallowigi** [comment]
Done. Enjoy!

**Comment by TamasBarta** [comment]
That was fast :) Thanks for taking your time. However, I ran into issues. I can see the new option, and it's exactly how I imagined it, but it doesn't apply the font I specify. I tried setting it under the tweaks menu, and also tried toggling it in the title bar. It works well for the regular font override. I'm using latest of both Slack, and mtslack.

**Comment by mallowigi** [comment]
Maybe you didn't add the font size at the top?

**Comment by TamasBarta** [comment]
Ah, I missed that. Maybe you also should note that a unit is required as well. It didn't work for me with "15 Jetbrains Mono", but it worked with "15px Jetbrains Mono". Thanks for this cool feature! 🙂
