### ISSUE TITLE
Theme isn't applied

### ISSUE THREAD

**Issue by diegobersano** [mallowigi/slack-themes#6]
First at all, good job! It's look really well.
I'm trying to apply the theme in a MacOS and I can't. I didn't receive any error message, I just open Slack after apply the theme and it isn't have any change.
Is there any logs folder where I can check for error messages?
Thanks!

**Comment by Kryan90** [comment]
Having the same issue this morning. Tried removing and re-adding, but no luck.

**Comment by mallowigi** [comment]
oops i removed the styles by mistake....................... fixing 🤦‍♂
