### ISSUE TITLE
Readme incorrect?

### ISSUE THREAD

**Issue by ghost** [mallowigi/slack-themes#9]
Why does it start off saying only works for Mac if that's not the case? That line should probably be updated to be accurate, or removed. Confusing people.

**Comment by mallowigi** [comment]
I don’t know I didn’t manage to make it work on Windows at the moment, some issues with permissions. And for Linux it only works when installing from the website and not from the marketplace

**Comment by xbold** [comment]
Should it say that it works on Mac OS and the non-snap version on Linux? So
people don't have to guess or don't bother scrolling down to the Linux
instructions?
